Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/collect/MapMaker
	at org.python.core.PyType.fromClass(PyType.java:1355)
	at org.python.core.PyObject.<init>(PyObject.java:97)
	at org.python.core.PyBuiltinCallable.<init>(PyBuiltinCallable.java:24)
	at org.python.core.PyBuiltinMethod.<init>(PyBuiltinMethod.java:16)
	at org.python.core.PyBuiltinMethod.<init>(PyBuiltinMethod.java:21)
	at org.python.core.PyType$type___init___exposer.<init>(Unknown Source)
	at org.python.core.PyType$PyExposer.<init>(Unknown Source)
	at org.python.core.PyType.<clinit>(PyType.java)
	at org.python.core.PyObject.<init>(PyObject.java:97)
	at org.python.core.PyBuiltinCallable.<init>(PyBuiltinCallable.java:24)
	at org.python.core.PyBuiltinMethod.<init>(PyBuiltinMethod.java:16)
	at org.python.core.PyBuiltinMethodNarrow.<init>(PyBuiltinMethodNarrow.java:23)
	at org.python.core.PyDataDescr$getset_descriptor___get___exposer.<init>(Unknown Source)
	at org.python.core.PyDataDescr$PyExposer.<init>(Unknown Source)
	at org.python.core.PyDataDescr.<clinit>(PyDataDescr.java)
	at org.python.core.PyBuiltinCallable$PyExposer.<init>(Unknown Source)
	at org.python.core.PyBuiltinCallable.<clinit>(PyBuiltinCallable.java)
	at org.python.core.PyObject$PyExposer.<init>(Unknown Source)
	at org.python.core.PyObject.<clinit>(PyObject.java)
	at org.python.util.jython.run(jython.java:232)
	at org.python.util.jython.main(jython.java:141)
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.MapMaker
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 21 more
